provider: aws
aws:
  region: ${aws_region}
  zoneType: ${aws_zone_type}
sources:
  - service
  - ingress
logFormat: json
policy: upsert-only
rbac:
  create: true
  pspEnabled: false
serviceAccount:
  create: true
  name: ${external_dns_eks_service_account}
  annotations:
    eks.amazonaws.com/role-arn: ${aws_iam_role_external_dns_arn}
