provider: aws
aws:
  region: ${aws_region}
  zoneType: ${aws_zone_type}
sources:
  - service
  - ingress
logFormat: json
policy: sync
rbac:
  create: true
  pspEnabled: false
serviceAccount:
  create: true
  name: ${external_dns_eks_service_account}
  annotations:
    eks.amazonaws.com/role-arn: ${aws_iam_role_external_dns_arn}
zoneIdFilters: ["${aws_public_hosted_zone}"]
annotationFilter: "alb.ingress.kubernetes.io/scheme=internet-facing"
txtOwnerId: ${eks_cluster_id}

%{ if anytrue([image_registry != null, image_repository != null, image_tag != null]) ~}
image:
%{ if image_registry != null ~}
  registry: ${image_registry}
%{ endif ~}
%{ if image_repository != null ~}
  repository: ${image_repository}
%{ endif ~}
%{ if image_tag != null ~}
  tag: ${image_tag}
%{ endif ~}
%{ endif ~}
